import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GrabLoader } from "@/components/grab-loader";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={inter.variable}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/sun-typeface/SUIT@2/fonts/static/woff2/SUIT.css"
          crossOrigin="anonymous"
        />
      </head>
      <body className="antialiased">
        {process.env.NODE_ENV === "development" && <GrabLoader />}
        {children}
      </body>
    </html>
  );
}
